<?php
//
// ETS2MP Homepage language file.
// File:				english.php
// Language name: 		English
// Translated name: 	English
//
$_lang["download"] = "Hent";
$_lang["home"] = "Hjem";
$_lang["status"] = "Status";
$_lang["username"] = "Brugernavn";
$_lang["password"] = "Kode";
$_lang["login"] = "Log ind";
$_lang["register"] = "Registrer";
$_lang["download.latest.version"] = "Hent seneste version";
$_lang["current.release"] = "Nuværende udgave:";
$_lang["language"] = "Sprog";
$_lang["join"] = "Deltag";
$_lang["mainpage.join"] = "Vær med og deltag sammen med tusinde lastbil interesserede spillere!";
$_lang["ts3.advertisement"] = "Kommunikér med andre chauffører over vores TeamSpeak 3!";
$_lang["facebook.advertisement"] = "Få de seneste status opdateringer på vores facebookside!";
$_lang["registration.blocked"] = "Registrering er i øjeblikket blokeret, da vi følte dette var nødvendigt, eftersom vi arbejder hårdt på at udgive nye opdateringer. Vi vil åbne registrering så hurtigt som muligt.";
$_lang["invalid.username.password"] = "Ugyldig email eller kodeord.";
$_lang["already.logged"] = "Du er allerede logget ind.";
$_lang["welcome"] = "Velkommen!";
$_lang["logout"] = "Log ud";
$_lang["bans"] = "Forbud";
$_lang["version"] = "Version";
$_lang["update.time"] = "Opdaterings tid";
$_lang["req.game.version"] = "Nødvendig spil version:";
$_lang["requires"] = "Skal bruge";
$_lang["or.newer"] = "Eller nyere";
$_lang["game.client"] = "Spil Klient";
$_lang["download.no.permissions"] = "Du skal være logget ind for at hente dette.";
$_lang["why.create.account"] = "Hvorfor lave en bruger?<br />Med en bruger kan du være logget ind på alle de forskellige servicer (forum, spil, økonomien og andre). Vi har planer om at bruge dem til at introducere økonomier og personlige chaufførers statistikker i fremtiden. Du vil være i stand til at tilpasse din egen profil.";
$_lang["website.title"] = "ETS2MP - Virtel lastbil kørsel - Multiplayer modificering for Euro Truck Simulator 2 Et spil af SCS Software";
$_lang["cookies.warning"] = "Denne side bruger <a href=\"http://en.wikipedia.org/wiki/HTTP_cookie\">cookies</a>. Hvis du fortsætter med at browse på denne side, vil du samtidig tillade vores brug af cookies.";
$_lang["forum"] = "Forum";
$_lang["cannot.create.account.when.logged"] = "Du kan ikke oprette en ny bruger, mens du er logget ind med en anden.";
$_lang["successfully.registered"] = "Din registraion blev en succes! Vær venlig og tjek din email for at aktivere din bruger.";
$_lang["error.unknown"] = "Ukendt fejl";
$_lang["credentials.taken"] = "Brugernavn, email eller Steam ID er allerede taget.";
$_lang["error.no.steam.data"] = "For at lave en ETS2MP bruger, må du have ETS2 forbundet til din Steam bruger. Hvis du har ETS2 i dit Steam bibliotek, så prøv og tjek om din profil er offentliggjort. Hvis den er privat, så sørg for den bliver offentliggjort og tryk.";
$_lang["register.steam.info"] = "For at registrere skal du logge ind på din Steam bruger. Tryk på knappen nedenunder for at komme ind på Steams bekræfteleses side.";
$_lang["rules.info"] = "Når du trykker på Registrer knappen, vil du automatisk acceptere vores fællesskabs regler. For at tjekke reglerne, klik her.";
$_lang["mail"] = "E-Mail";
$_lang["repeat.mail"] = "Gentag email";
$_lang["new.password"] = "Nyt kodeord";
$_lang["repeat.new.password"] = "Gentag nyt kodeord";
$_lang["new.password.summary"] = "Hvis du forlader disse felter blanke, vil dit kodeord ikke forandres.";
$_lang["old.password"] = "Gamle kodeord";
$_lang["repeat.old.password"] = "Gentag gamle kodeord";
$_lang["save.account.data"] = "Gem account data";
$_lang["edit.account"] = "Redigér account.";
$_lang["forgot.password"] = "Glemt kodeord? Klik <a href=\"index.php?page=resetPassword\">her</a>.";
$_lang["forgot.password.summary"] = "Har du glemt dit kodeord? Skriv din mail nedenunder og tryk på \"Påmind kodeord\" knappen.";
$_lang["reminder.button"] = "Påmind kodeord";
$_lang["reset.password"] = "Nulstil kodeord";
$_lang["password.reminder.mail.title"] = "Kodeord påmindelses bekræftelse.";
$_lang["password.reminder.content"] = "Hej.\n\nNogen fra ip {0} ansøgte om at nulstille dit kodeord for din ETS2MP account.\n\nFor at nulstille dit kodeord klik på dette link:  {1}.\nHvis det ikke var dig, så vær venlig og ignorer denne mail. \n\nHilsen\nETS2MP Team";
$_lang["new.password.mail.title"] = "Dit nye kodeord.";
$_lang["new.password.mail.content"] = "Hej.\n\nDette er dit nye kodeord: {0}\n\nHusk at skift det øjeblikkeligt efter at have logget ind. \n\nHilsen\nETS2MP Team";
$_lang["account.activated"] = "Din account er succesfuldt aktiveret.";
$_lang["unable.to.activate"] = "Kunne ikke aktivere account, ugyldig nøgle eller account er allerede aktiveret.";
$_lang["not.activated"] = "Din account er ikke aktiveret endnu. Hvis du ikke har en aktiverings besked, klik <a href=\"index.php?action=resendActivation\">her</a> for at sende en aktiverings nøgle.";
$_lang["force.password.change"] = "Vær venlig at skifte dit kodeord øjeblikkeligt. Klik <a href=\"index.php?page=editAccount\">her</a> for at gøre det.";
$_lang["forgot.password.link.sent"] = "Tjek din e-mail. Vi har sendt dig et kodeord nulstilings link. ";
$_lang["forgot.password.sent"] = "Tjek din e-mail. Vi har sendt dig et nyt kodeord.";
$_lang["forgot.password.invalid.key"] = "Ugyldigt kodeord nulstillings nøgle.";
$_lang["activation.key.resent"] = "Ny aktiverings nøgle er blevet sendt til din e-mail.";
$_lang["activation.mail.title"] = "ETS2MP account aktivering.";
$_lang["activation.mail.content"] = "Hej.\n\nDette er din aktiverings nøgle:  {0}\n\nHilsen\nETS2MP Team";
$_lang["no.login"] = "Du er nødt til at være logget ind, for at få tilladelse til denne side.";
$_lang["settings.saved.with.mail"] = "Account er blevet gemt. Tjek din e-mail og aktiver account igen.";
$_lang["new.email.in.use"] = "Denne email er allerede taget i brug.";
$_lang["email.does.not.match"] = "Oplyste emails matcher ikke.";
$_lang["invalid.email.format"] = "E-Mail som du har oplyst, er ikke gyldig.";
$_lang["new.password.does.not.match"] = "Det nye kodeord du har oplyst mathcer ikke.";
$_lang["too.short.password"] = "Det nye kodeord er for kort. Minimum: 5 karakterer";
$_lang["old.password.does.not.match"] = "Gamle kodeord matcher ikke.";
$_lang["settings.saved"] = "Accounten er blevet gemt.";
$_lang["invalid.old.password"] = "Det gamle kodeord er ugyldigt, kan ikke gemme account.";
$_lang["no.password.change.forced"] = "For at nulstille dit kodeord, skal du være logget ud.";
$_lang["password.reminder.edit.account"] = "Kan du ikke huske dit kodeord? Klik <a href=\"index.php?page=resetPassword\">her</a>.";
$_lang["contact"] = "Kontakt";
$_lang["your.mail"] = "Din e-mail";
$_lang["content"] = "Indhold";
$_lang["send"] = "Send";
$_lang["contact.message.sent"] = "Tak fordi du kontaktede os. Vær venlig og vent for tilbagemelding.";
$_lang["topic"] = "Tråd";
$_lang["contact.message.too.short"] = "Beskeden er for kort. Minimum 10 karakterer.";
$_lang["contact.topic.too.short"] = "Tråden er for kort. Minimum 10 karakterer.";
$_lang["invalid.mail.forgot.password"] = "Vi kunne ikke finde nogen account med denne mail.";
$_lang["steamid.in.use"] = "Vi har fundet en ETS2MP account som allerede er forbundet til denne Steam account. Hvis du har nogle problemer med registrering bedes du  <a href=\"http://ets2mp.com/support/\">lave en support billet.</a>.";
$_lang["mail.does.not.match"] = "Den givne e-mail addresse matcher ikke.";
$_lang["support"] = "Support";
$_lang["profile"] = "Profil";
$_lang["group"] = "Gruppe";
$_lang["banned"] = "Udelukket";
$_lang["state"] = "Stat";
$_lang["account.is.activated"] = "Account er blevet aktiveret";
$_lang["account.isnt.activated"] = "Account er ikke aktiveret";
$_lang["penalty.history"] = "Straffe historik";
$_lang["no.punishments"] = "Ingen straffe at vise.";
$_lang["date"] = "Dato";
$_lang["reason"] = "Grund";
$_lang["type"] = "Type";
$_lang["penalty.limit"] = "Kun ejeren at denne profil kan se længere historik med straffe.";
